# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import qall_registry_client.v1.client.protobuf.registry_api_v1.registry_api_v1_pb2 as registry__api__v1__pb2

GRPC_GENERATED_VERSION = "1.71.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in registry_api_v1_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServiceInfo = channel.unary_unary(
            "/registry_api_v1.Api/GetServiceInfo",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=registry__api__v1__pb2.RegistryInfo.FromString,
            _registered_method=True,
        )
        self.Check = channel.unary_unary(
            "/registry_api_v1.Api/Check",
            request_serializer=registry__api__v1__pb2.CheckRequest.SerializeToString,
            response_deserializer=registry__api__v1__pb2.CheckResponse.FromString,
            _registered_method=True,
        )
        self.Push = channel.unary_unary(
            "/registry_api_v1.Api/Push",
            request_serializer=registry__api__v1__pb2.PushRequest.SerializeToString,
            response_deserializer=registry__api__v1__pb2.PushResponse.FromString,
            _registered_method=True,
        )
        self.Get = channel.unary_unary(
            "/registry_api_v1.Api/Get",
            request_serializer=registry__api__v1__pb2.GetRequest.SerializeToString,
            response_deserializer=registry__api__v1__pb2.GetResponse.FromString,
            _registered_method=True,
        )
        self.Tag = channel.unary_unary(
            "/registry_api_v1.Api/Tag",
            request_serializer=registry__api__v1__pb2.TagRequest.SerializeToString,
            response_deserializer=registry__api__v1__pb2.TagResponse.FromString,
            _registered_method=True,
        )
        self.Resolve = channel.unary_unary(
            "/registry_api_v1.Api/Resolve",
            request_serializer=registry__api__v1__pb2.ResolveRequest.SerializeToString,
            response_deserializer=registry__api__v1__pb2.ResolveResponse.FromString,
            _registered_method=True,
        )
        self.ListTags = channel.unary_unary(
            "/registry_api_v1.Api/ListTags",
            request_serializer=registry__api__v1__pb2.ListTagsRequest.SerializeToString,
            response_deserializer=registry__api__v1__pb2.ListTagsResponse.FromString,
            _registered_method=True,
        )
        self.Untag = channel.unary_unary(
            "/registry_api_v1.Api/Untag",
            request_serializer=registry__api__v1__pb2.UntagRequest.SerializeToString,
            response_deserializer=registry__api__v1__pb2.UntagResponse.FromString,
            _registered_method=True,
        )


class ApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetServiceInfo(self, request, context):
        """
        General methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Check(self, request, context):
        """Check which hashes are already known by the registry.
        Client sends a list of hashes it wants to push.
        Registry returns the subset that are missing (need upload).
        This is the core delta-push mechanism: only upload what's new.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Push(self, request, context):
        """Upload a batch of blocks. Only missing blocks should be sent
        (use Check first). Uploading an existing block is a no-op (idempotent).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Get(self, request, context):
        """Retrieve a block by hash. Used by the execution service to fetch tasks."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Tag(self, request, context):
        """Register or update a named workflow tag pointing to a root node hash.
        Equivalent to `docker tag`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Resolve(self, request, context):
        """Resolve a workflow name+version to its root node hash."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTags(self, request, context):
        """List all versions of a workflow."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Untag(self, request, context):
        """Delete a workflow tag (does not GC blocks, blocks are ref-counted)."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetServiceInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetServiceInfo,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=registry__api__v1__pb2.RegistryInfo.SerializeToString,
        ),
        "Check": grpc.unary_unary_rpc_method_handler(
            servicer.Check,
            request_deserializer=registry__api__v1__pb2.CheckRequest.FromString,
            response_serializer=registry__api__v1__pb2.CheckResponse.SerializeToString,
        ),
        "Push": grpc.unary_unary_rpc_method_handler(
            servicer.Push,
            request_deserializer=registry__api__v1__pb2.PushRequest.FromString,
            response_serializer=registry__api__v1__pb2.PushResponse.SerializeToString,
        ),
        "Get": grpc.unary_unary_rpc_method_handler(
            servicer.Get,
            request_deserializer=registry__api__v1__pb2.GetRequest.FromString,
            response_serializer=registry__api__v1__pb2.GetResponse.SerializeToString,
        ),
        "Tag": grpc.unary_unary_rpc_method_handler(
            servicer.Tag,
            request_deserializer=registry__api__v1__pb2.TagRequest.FromString,
            response_serializer=registry__api__v1__pb2.TagResponse.SerializeToString,
        ),
        "Resolve": grpc.unary_unary_rpc_method_handler(
            servicer.Resolve,
            request_deserializer=registry__api__v1__pb2.ResolveRequest.FromString,
            response_serializer=registry__api__v1__pb2.ResolveResponse.SerializeToString,
        ),
        "ListTags": grpc.unary_unary_rpc_method_handler(
            servicer.ListTags,
            request_deserializer=registry__api__v1__pb2.ListTagsRequest.FromString,
            response_serializer=registry__api__v1__pb2.ListTagsResponse.SerializeToString,
        ),
        "Untag": grpc.unary_unary_rpc_method_handler(
            servicer.Untag,
            request_deserializer=registry__api__v1__pb2.UntagRequest.FromString,
            response_serializer=registry__api__v1__pb2.UntagResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "registry_api_v1.Api", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("registry_api_v1.Api", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Api(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetServiceInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/GetServiceInfo",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            registry__api__v1__pb2.RegistryInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Check(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/Check",
            registry__api__v1__pb2.CheckRequest.SerializeToString,
            registry__api__v1__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Push(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/Push",
            registry__api__v1__pb2.PushRequest.SerializeToString,
            registry__api__v1__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Get(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/Get",
            registry__api__v1__pb2.GetRequest.SerializeToString,
            registry__api__v1__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Tag(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/Tag",
            registry__api__v1__pb2.TagRequest.SerializeToString,
            registry__api__v1__pb2.TagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Resolve(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/Resolve",
            registry__api__v1__pb2.ResolveRequest.SerializeToString,
            registry__api__v1__pb2.ResolveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTags(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/ListTags",
            registry__api__v1__pb2.ListTagsRequest.SerializeToString,
            registry__api__v1__pb2.ListTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Untag(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/registry_api_v1.Api/Untag",
            registry__api__v1__pb2.UntagRequest.SerializeToString,
            registry__api__v1__pb2.UntagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
