// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: registry-api-v1.proto

package registry_api_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A Block is the universal storage unit in the registry.
// Everything (payload, node, constraints) is a Block.
// The registry is content-addressed: the hash IS the identity.
// The registry doesn't care what the data means, it just stores bytes.
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"` // Content Identifier (CID)
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // canonical JSON-encoded object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_registry_api_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *Block) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A Tag is the only named, versioned object in the registry.
// It is a pointer to a root node hash, nothing more.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                         // e.g. "my_vqe"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                   // e.g. "v1" or "latest"
	RootHash      string                 `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"` // hash of the root block
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_registry_api_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{1}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Tag) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

type RegistryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryInfo) Reset() {
	*x = RegistryInfo{}
	mi := &file_registry_api_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryInfo) ProtoMessage() {}

func (x *RegistryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryInfo.ProtoReflect.Descriptor instead.
func (*RegistryInfo) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{2}
}

func (x *RegistryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistryInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_registry_api_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{3}
}

func (x *CheckRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hashes from the request that the registry does NOT have yet.
	MissingHashes []string `protobuf:"bytes,1,rep,name=missing_hashes,json=missingHashes,proto3" json:"missing_hashes,omitempty"`
	TotalCount    int32    `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_registry_api_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{4}
}

func (x *CheckResponse) GetMissingHashes() []string {
	if x != nil {
		return x.MissingHashes
	}
	return nil
}

func (x *CheckResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type PushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushRequest) Reset() {
	*x = PushRequest{}
	mi := &file_registry_api_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushRequest) ProtoMessage() {}

func (x *PushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushRequest.ProtoReflect.Descriptor instead.
func (*PushRequest) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{5}
}

func (x *PushRequest) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type PushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of blocks actually written (already-present blocks skipped).
	WrittenBlocksCount int32 `protobuf:"varint,1,opt,name=written_blocks_count,json=writtenBlocksCount,proto3" json:"written_blocks_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	mi := &file_registry_api_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{6}
}

func (x *PushResponse) GetWrittenBlocksCount() int32 {
	if x != nil {
		return x.WrittenBlocksCount
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashes        []string               `protobuf:"bytes,1,rep,name=hashes,proto3" json:"hashes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_registry_api_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{7}
}

func (x *GetRequest) GetHashes() []string {
	if x != nil {
		return x.Hashes
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_registry_api_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{8}
}

func (x *GetResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *GetResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           *Tag                   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagRequest) Reset() {
	*x = TagRequest{}
	mi := &file_registry_api_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagRequest) ProtoMessage() {}

func (x *TagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagRequest.ProtoReflect.Descriptor instead.
func (*TagRequest) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{9}
}

func (x *TagRequest) GetTag() *Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

type TagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The canonical workflow URI: "<name>:<version>"
	Uri           string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_registry_api_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{10}
}

func (x *TagResponse) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_registry_api_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResolveRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootHash      string                 `protobuf:"bytes,1,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_registry_api_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveResponse) GetRootHash() string {
	if x != nil {
		return x.RootHash
	}
	return ""
}

type ListTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsRequest) Reset() {
	*x = ListTagsRequest{}
	mi := &file_registry_api_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsRequest) ProtoMessage() {}

func (x *ListTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsRequest.ProtoReflect.Descriptor instead.
func (*ListTagsRequest) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{13}
}

func (x *ListTagsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []*Tag                 `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagsResponse) Reset() {
	*x = ListTagsResponse{}
	mi := &file_registry_api_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagsResponse) ProtoMessage() {}

func (x *ListTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagsResponse.ProtoReflect.Descriptor instead.
func (*ListTagsResponse) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{14}
}

func (x *ListTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListTagsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type UntagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntagRequest) Reset() {
	*x = UntagRequest{}
	mi := &file_registry_api_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntagRequest) ProtoMessage() {}

func (x *UntagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntagRequest.ProtoReflect.Descriptor instead.
func (*UntagRequest) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{15}
}

func (x *UntagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UntagRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UntagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UntagResponse) Reset() {
	*x = UntagResponse{}
	mi := &file_registry_api_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UntagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UntagResponse) ProtoMessage() {}

func (x *UntagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_registry_api_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UntagResponse.ProtoReflect.Descriptor instead.
func (*UntagResponse) Descriptor() ([]byte, []int) {
	return file_registry_api_v1_proto_rawDescGZIP(), []int{16}
}

func (x *UntagResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_registry_api_v1_proto protoreflect.FileDescriptor

const file_registry_api_v1_proto_rawDesc = "" +
	"\n" +
	"\x15registry-api-v1.proto\x12\x0fregistry_api_v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/api/annotations.proto\"/\n" +
	"\x05Block\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"P\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1b\n" +
	"\troot_hash\x18\x03 \x01(\tR\brootHash\"<\n" +
	"\fRegistryInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"&\n" +
	"\fCheckRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"W\n" +
	"\rCheckResponse\x12%\n" +
	"\x0emissing_hashes\x18\x01 \x03(\tR\rmissingHashes\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"=\n" +
	"\vPushRequest\x12.\n" +
	"\x06blocks\x18\x01 \x03(\v2\x16.registry_api_v1.BlockR\x06blocks\"@\n" +
	"\fPushResponse\x120\n" +
	"\x14written_blocks_count\x18\x01 \x01(\x05R\x12writtenBlocksCount\"$\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x06hashes\x18\x01 \x03(\tR\x06hashes\"^\n" +
	"\vGetResponse\x12.\n" +
	"\x06blocks\x18\x01 \x03(\v2\x16.registry_api_v1.BlockR\x06blocks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"4\n" +
	"\n" +
	"TagRequest\x12&\n" +
	"\x03tag\x18\x01 \x01(\v2\x14.registry_api_v1.TagR\x03tag\"\x1f\n" +
	"\vTagResponse\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\">\n" +
	"\x0eResolveRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\".\n" +
	"\x0fResolveResponse\x12\x1b\n" +
	"\troot_hash\x18\x01 \x01(\tR\brootHash\"%\n" +
	"\x0fListTagsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"]\n" +
	"\x10ListTagsResponse\x12(\n" +
	"\x04tags\x18\x01 \x03(\v2\x14.registry_api_v1.TagR\x04tags\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"<\n" +
	"\fUntagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\")\n" +
	"\rUntagResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted2\x89\x06\n" +
	"\x03Api\x12T\n" +
	"\x0eGetServiceInfo\x12\x16.google.protobuf.Empty\x1a\x1d.registry_api_v1.RegistryInfo\"\v\x82\xd3\xe4\x93\x02\x05\x12\x03/v1\x12c\n" +
	"\x05Check\x12\x1d.registry_api_v1.CheckRequest\x1a\x1e.registry_api_v1.CheckResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/blocks/check\x12W\n" +
	"\x04Push\x12\x1c.registry_api_v1.PushRequest\x1a\x1d.registry_api_v1.PushResponse\"\x12\x82\xd3\xe4\x93\x02\f\"\n" +
	"/v1/blocks\x12T\n" +
	"\x03Get\x12\x1b.registry_api_v1.GetRequest\x1a\x1c.registry_api_v1.GetResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/blocks\x12R\n" +
	"\x03Tag\x12\x1b.registry_api_v1.TagRequest\x1a\x1c.registry_api_v1.TagResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\"\b/v1/tags\x12o\n" +
	"\aResolve\x12\x1f.registry_api_v1.ResolveRequest\x1a .registry_api_v1.ResolveResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/tags/{name}/{version}\x12h\n" +
	"\bListTags\x12 .registry_api_v1.ListTagsRequest\x1a!.registry_api_v1.ListTagsResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/tags/{name}\x12i\n" +
	"\x05Untag\x12\x1d.registry_api_v1.UntagRequest\x1a\x1e.registry_api_v1.UntagResponse\"!\x82\xd3\xe4\x93\x02\x1b*\x19/v1/tags/{name}/{version}B*Z(internal/server/protobuf/registry_api_v1b\x06proto3"

var (
	file_registry_api_v1_proto_rawDescOnce sync.Once
	file_registry_api_v1_proto_rawDescData []byte
)

func file_registry_api_v1_proto_rawDescGZIP() []byte {
	file_registry_api_v1_proto_rawDescOnce.Do(func() {
		file_registry_api_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_registry_api_v1_proto_rawDesc), len(file_registry_api_v1_proto_rawDesc)))
	})
	return file_registry_api_v1_proto_rawDescData
}

var file_registry_api_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_registry_api_v1_proto_goTypes = []any{
	(*Block)(nil),            // 0: registry_api_v1.Block
	(*Tag)(nil),              // 1: registry_api_v1.Tag
	(*RegistryInfo)(nil),     // 2: registry_api_v1.RegistryInfo
	(*CheckRequest)(nil),     // 3: registry_api_v1.CheckRequest
	(*CheckResponse)(nil),    // 4: registry_api_v1.CheckResponse
	(*PushRequest)(nil),      // 5: registry_api_v1.PushRequest
	(*PushResponse)(nil),     // 6: registry_api_v1.PushResponse
	(*GetRequest)(nil),       // 7: registry_api_v1.GetRequest
	(*GetResponse)(nil),      // 8: registry_api_v1.GetResponse
	(*TagRequest)(nil),       // 9: registry_api_v1.TagRequest
	(*TagResponse)(nil),      // 10: registry_api_v1.TagResponse
	(*ResolveRequest)(nil),   // 11: registry_api_v1.ResolveRequest
	(*ResolveResponse)(nil),  // 12: registry_api_v1.ResolveResponse
	(*ListTagsRequest)(nil),  // 13: registry_api_v1.ListTagsRequest
	(*ListTagsResponse)(nil), // 14: registry_api_v1.ListTagsResponse
	(*UntagRequest)(nil),     // 15: registry_api_v1.UntagRequest
	(*UntagResponse)(nil),    // 16: registry_api_v1.UntagResponse
	(*emptypb.Empty)(nil),    // 17: google.protobuf.Empty
}
var file_registry_api_v1_proto_depIdxs = []int32{
	0,  // 0: registry_api_v1.PushRequest.blocks:type_name -> registry_api_v1.Block
	0,  // 1: registry_api_v1.GetResponse.blocks:type_name -> registry_api_v1.Block
	1,  // 2: registry_api_v1.TagRequest.tag:type_name -> registry_api_v1.Tag
	1,  // 3: registry_api_v1.ListTagsResponse.tags:type_name -> registry_api_v1.Tag
	17, // 4: registry_api_v1.Api.GetServiceInfo:input_type -> google.protobuf.Empty
	3,  // 5: registry_api_v1.Api.Check:input_type -> registry_api_v1.CheckRequest
	5,  // 6: registry_api_v1.Api.Push:input_type -> registry_api_v1.PushRequest
	7,  // 7: registry_api_v1.Api.Get:input_type -> registry_api_v1.GetRequest
	9,  // 8: registry_api_v1.Api.Tag:input_type -> registry_api_v1.TagRequest
	11, // 9: registry_api_v1.Api.Resolve:input_type -> registry_api_v1.ResolveRequest
	13, // 10: registry_api_v1.Api.ListTags:input_type -> registry_api_v1.ListTagsRequest
	15, // 11: registry_api_v1.Api.Untag:input_type -> registry_api_v1.UntagRequest
	2,  // 12: registry_api_v1.Api.GetServiceInfo:output_type -> registry_api_v1.RegistryInfo
	4,  // 13: registry_api_v1.Api.Check:output_type -> registry_api_v1.CheckResponse
	6,  // 14: registry_api_v1.Api.Push:output_type -> registry_api_v1.PushResponse
	8,  // 15: registry_api_v1.Api.Get:output_type -> registry_api_v1.GetResponse
	10, // 16: registry_api_v1.Api.Tag:output_type -> registry_api_v1.TagResponse
	12, // 17: registry_api_v1.Api.Resolve:output_type -> registry_api_v1.ResolveResponse
	14, // 18: registry_api_v1.Api.ListTags:output_type -> registry_api_v1.ListTagsResponse
	16, // 19: registry_api_v1.Api.Untag:output_type -> registry_api_v1.UntagResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_registry_api_v1_proto_init() }
func file_registry_api_v1_proto_init() {
	if File_registry_api_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_registry_api_v1_proto_rawDesc), len(file_registry_api_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_registry_api_v1_proto_goTypes,
		DependencyIndexes: file_registry_api_v1_proto_depIdxs,
		MessageInfos:      file_registry_api_v1_proto_msgTypes,
	}.Build()
	File_registry_api_v1_proto = out.File
	file_registry_api_v1_proto_goTypes = nil
	file_registry_api_v1_proto_depIdxs = nil
}
